import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Locale } from '../../../i18n-config'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const strawfond = localFont({
    src: [
        {
            path: '../../../public/strawford/Strawford-Regular.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../../public/strawford/Strawford-Medium.otf',
            weight: '500',
            style: 'medium',
        },
    ],
    variable: '--strawford',
})

export default function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode
    params: { lang: Locale }
}>) {
    return (
        <html lang={params.lang}>
            <body className={`${strawfond.variable} ${strawfond.className}`}>{children}</body>
        </html>
    )
}
