import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const strawfond = localFont({
	src: [
		{
			path: '../../public/strawford/Strawford-Regular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../public/strawford/Strawford-Medium.otf',
			weight: '500',
			style: 'medium',
		},
	],
	variable: '--strawford',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${strawfond.variable} ${strawfond.className}`}>{children}</body>
		</html>
	)
}
